#!/bin/bash
# SPDX-License-Identifier: LGPL-2.1-or-later

set -eux

if [[ -z "${MKOSI_CONFIG-}" ]]; then
    exec mkosi \
        --directory "${LWORKSPACE}" \
        --build-script= \
        --build-script="$(realpath "$0")" \
        --rerun-build-scripts \
        build \
        -- \
        "$@"
fi

HOST_BUILDSUBDIR="$(jq -r .BuildSubdirectory "${MKOSI_CONFIG}")"

BUILD_SOURCE_MAPPINGS="$(jq -r '
    .BuildSources
    | sort_by(.Target)
    | reverse
    | map(.Source + "=/work/src/" + .Target)
    | join(",")
' "${MKOSI_CONFIG}")"

exec mkosi-chroot env clangd \
    --enable-config \
    --path-mappings="\
$BUILD_SOURCE_MAPPINGS,\
$HOST_BUILDSUBDIR=/work/build" \
    "$@"
